#!/bin/bash
merge conflict
echo "ALX School"
echo "ALX school is so cool! " 
#!/bin/bash
echo "ALX school is so cool! "

echo "ALX school" 
#!/bin/bash
echo "ALX school"


































































